input RegisterInput {
  email: String!
  password: String!
}
input LoginInput {
  email: String!
  password: String!
}
type User {
  id: ID!
  email: String!
  inventory: [Item]
  inventoryCount: Int!
  createdAt: String!
}
extend type Query {
  findUserById(userId: ID!): User
  getMe: User
}
extend type Mutation {
  register(registerInput: RegisterInput!): User!
  login(loginInput: LoginInput!): User!
  logout: String
}